### ISSUE TITLE
Faucet for Testnet

### ISSUE THREAD

**Issue by b00f** [pactus-project/pactus#214]
### Describe the problem you'd like to have solved

User should be able to use TestNet for sending test transactions. In order to give test coins, we have to  Faucet for the TestNet. Something similar to: https://bitcoinfaucet.uo1.net/

### Describe the ideal solution

We can give some test coins per request. 

## Alternatives and current work-arounds

The only workaround for user to send test transaction is running a local net:
```
zarb init -w ~/zarb//local
zarb start -w ~/zarb//local
```

**Comment by d4rk5h0t** [comment]
I would suggest to have it as separate free transaction so the treasury will send some coins to applier just once.

we can allow this transaction only once per account and may limit the amount or specified in request transaction

this way all test nets will have same way of resource application mechanism rather than centralized webpages with per-mined coins
but it might have some over head on network and needs to be explicitly ON on test-nets

the payload may look like
```
payload:{
       for:"zrb1....",
       amount:200
}
```
and validators will append a transaction from treasury to the address specified in payload with amount requested

**Comment by b00f** [comment]
The faucet project is under development. @nagarajmanjunath please close this issue when the faucet is ready.
